# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'GroupProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Parse'
 	pod 'AlamofireImage'
	pod 'MBProgressHUD'
	pod 'CameraManager', '~> 5.1'
	pod 'DropDown'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'MessageKit'
	pod 'RealmSwift'

  # Pods for GroupProject


  target 'GroupProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupProjectUITests' do
    # Pods for testing
  end

end
